---
name: "drink-x"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    container_name: flask
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    environment:
      LANG: "en_US.UTF-8"
      LC_COLLATE: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_HOST: ${POSTGRES_HOST?Variable not set}
      POSTGRES_PORT: ${POSTGRES_PORT?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
    restart: "unless-stopped"
    depends_on:
      db:
        condition: "service_healthy"
