---
name: "drink-x"
services:
  db:
    image: postgres:15.8-alpine
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgresql/final:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      LC_COLLATE: "en_US.UTF-8"
      LC_CTYPE: "en_US.UTF-8"
    restart: "no"
    healthcheck:
      test:
        - "CMD"
        - "pg_isready"
        - "-h"
        - "localhost"
        - "-p"
        - "5432"
        - "-U"
        - "postgres"
        - "-d"
        - "postgres"
      interval: "10s"
      timeout: "10s"
      retries: 10
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_min_duration_statement=50"
volumes:
  postgres-data:
