# ==== COMMANDS TO RUN FILE ===
# docker-compose up -d
# =============================

services:
  # build backend (backend's Dockerfile is in ./backend/Dockerfile.backend)
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
      
  # build frontend (frontend's Dockerfile is in ./Dockerfile.frontend)
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    # depends_on:
    # - backend

  # build postgres db
  db:
    image: postgres:15.8
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/postgresql/final:/docker-entrypoint-initdb.d  # Use your custom directory name
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
      POSTGRES_USER: drinkx
      POSTGRES_DB: drinkx
volumes:
  postgres-data: