version: '3'

services:
  create_listing:
    build:
      context: .
      dockerfile: Dockerfile
    command: python createListing.py
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase

  create_review:
    build:
      context: .
      dockerfile: Dockerfile
    command: python createReview.py
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
