name: Unit Tests

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-jest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run all jest tests
      run: |
        npm install
        npm test
  
  test-php:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: Install MySQL and MySQLi
      run: |
        sudo apt-get update
        sudo apt-get install mysql-server
        sudo service mysql start
        sudo apt-get install php-mysql
    - name: Run all php tests
      run: |
        phpunit unit_testing/DatabaseTest.php